import React from 'react';
import { Droplet, CloudLightning, Sun, ShieldAlert, Sprout, Info } from 'lucide-react';

interface Props {
  selectedCrop: string | null;
  todayRainfall: number;
}

export default function AgriculturalIntelligence({ selectedCrop, todayRainfall }: Props) {
  const isHighRain = todayRainfall > 15;

  return (
    <div className="flex flex-col gap-4 mt-2">
      
      {/* Disclaimer */}
      <div className="bg-amber-50/50 p-2.5 rounded-lg flex items-start gap-2 border border-amber-100">
        <Info className="text-amber-500 shrink-0 mt-0.5" size={14} />
        <div className="text-xs text-amber-700">
          <strong>Decision-support prototype.</strong> Interpretations are generated by static rules for demonstration purposes.
        </div>
      </div>

      <div className="grid grid-cols-2 gap-3">
        {/* Irrigation Need */}
        <div className="bg-white p-4 rounded-xl border border-gray-100 shadow-sm">
          <div className="flex items-center gap-2 mb-2">
            <Droplet size={18} className="text-blue-500"/>
            <h4 className="font-bold text-gray-700 text-sm">Irrigation</h4>
          </div>
          <div className="text-lg font-black text-gray-900 mb-1">
            {isHighRain ? "Monitor" : "Maintain"}
          </div>
          <p className="text-xs text-gray-500 leading-snug">
            {isHighRain 
              ? "Recent rainfall will likely reduce immediate irrigation requirements." 
              : "Standard irrigation schedules should be maintained."}
          </p>
        </div>

        {/* Field Activity */}
        <div className="bg-white p-4 rounded-xl border border-gray-100 shadow-sm">
          <div className="flex items-center gap-2 mb-2">
            <Sun size={18} className="text-amber-500"/>
            <h4 className="font-bold text-gray-700 text-sm">Field Work</h4>
          </div>
          <div className="text-lg font-black text-gray-900 mb-1">
             {isHighRain ? "Delay" : "Favorable"}
          </div>
          <p className="text-xs text-gray-500 leading-snug">
            {isHighRain 
              ? "Wet soil conditions may impede tractor usage and fertilizer application." 
              : "Weather is suitable for planned outdoor field activities."}
          </p>
        </div>
        
        {/* Pest Risk */}
        <div className="bg-white p-4 rounded-xl border border-gray-100 shadow-sm">
          <div className="flex items-center gap-2 mb-2">
            <ShieldAlert size={18} className="text-purple-500"/>
            <h4 className="font-bold text-gray-700 text-sm">Pest Risk</h4>
          </div>
          <div className="text-lg font-black text-gray-900 mb-1">
            {isHighRain ? "Elevated" : "Normal"}
          </div>
          <p className="text-xs text-gray-500 leading-snug">
             {isHighRain 
              ? "Humid conditions post-rainfall increase the risk of fungal infections." 
              : "Standard prophylactic monitoring recommended."}
          </p>
        </div>

        {/* Crop Context */}
        <div className="bg-emerald-50 p-4 rounded-xl border border-emerald-100 shadow-sm">
          <div className="flex items-center gap-2 mb-2">
            <Sprout size={18} className="text-emerald-600"/>
            <h4 className="font-bold text-emerald-800 text-sm">Crop Advisory</h4>
          </div>
          <div className="text-lg font-black text-emerald-900 mb-1">
             {selectedCrop ? selectedCrop : "Generic"}
          </div>
          <p className="text-xs text-emerald-700/80 leading-snug">
             {selectedCrop 
              ? `Advisory tailored for ${selectedCrop} growth stages.` 
              : "Please select a crop to receive tailored insights."}
          </p>
        </div>
      </div>

    </div>
  );
}
