import React from 'react';
import { Droplet, CloudLightning, Sun, ShieldAlert, Sprout, Info } from 'lucide-react';

interface Props {
  selectedCrop: string | null;
  todayRainfall: number;
}

export default function AgriculturalIntelligence({ selectedCrop, todayRainfall }: Props) {
  const isHighRain = todayRainfall > 15;

  return (
    <div className="flex flex-col gap-3 md:gap-4 mt-2">
      
      {/* Disclaimer */}
      <div className="bg-amber-50/50 p-2 md:p-2.5 rounded-lg flex items-start gap-2 border border-amber-100">
        <Info className="text-amber-500 shrink-0 mt-0.5 w-3.5 h-3.5 md:w-4 md:h-4" />
        <div className="text-[10px] md:text-xs text-amber-700 leading-tight">
          <strong>Decision-support prototype.</strong> Interpretations are generated by static rules for demonstration purposes.
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
        {/* Irrigation Need */}
        <div className="bg-white p-3 md:p-4 rounded-xl border border-gray-100 shadow-sm flex md:block items-center md:items-start gap-4 md:gap-0">
          <div className="flex flex-col md:flex-row md:items-center gap-1 md:gap-2 mb-0 md:mb-2 w-20 md:w-auto shrink-0">
            <Droplet size={18} className="text-blue-500 hidden md:block"/>
            <h4 className="font-bold text-gray-500 md:text-gray-700 text-[10px] md:text-sm uppercase tracking-wider md:tracking-normal md:normal-case">Irrigation</h4>
          </div>
          <div>
            <div className="text-base md:text-lg font-black text-gray-900 mb-0.5 md:mb-1">
              {isHighRain ? "Monitor" : "Maintain"}
            </div>
            <p className="text-[11px] md:text-xs text-gray-500 leading-snug">
              {isHighRain 
                ? "Recent rainfall will likely reduce immediate irrigation requirements." 
                : "Standard irrigation schedules should be maintained."}
            </p>
          </div>
        </div>

        {/* Field Activity */}
        <div className="bg-white p-3 md:p-4 rounded-xl border border-gray-100 shadow-sm flex md:block items-center md:items-start gap-4 md:gap-0">
          <div className="flex flex-col md:flex-row md:items-center gap-1 md:gap-2 mb-0 md:mb-2 w-20 md:w-auto shrink-0">
            <Sun size={18} className="text-amber-500 hidden md:block"/>
            <h4 className="font-bold text-gray-500 md:text-gray-700 text-[10px] md:text-sm uppercase tracking-wider md:tracking-normal md:normal-case">Field Work</h4>
          </div>
          <div>
            <div className="text-base md:text-lg font-black text-gray-900 mb-0.5 md:mb-1">
               {isHighRain ? "Delay" : "Favorable"}
            </div>
            <p className="text-[11px] md:text-xs text-gray-500 leading-snug">
              {isHighRain 
                ? "Wet soil conditions may impede tractor usage and fertilizer application." 
                : "Weather is suitable for planned outdoor field activities."}
            </p>
          </div>
        </div>
        
        {/* Pest Risk */}
        <div className="bg-white p-3 md:p-4 rounded-xl border border-gray-100 shadow-sm flex md:block items-center md:items-start gap-4 md:gap-0">
          <div className="flex flex-col md:flex-row md:items-center gap-1 md:gap-2 mb-0 md:mb-2 w-20 md:w-auto shrink-0">
            <ShieldAlert size={18} className="text-purple-500 hidden md:block"/>
            <h4 className="font-bold text-gray-500 md:text-gray-700 text-[10px] md:text-sm uppercase tracking-wider md:tracking-normal md:normal-case">Pest Risk</h4>
          </div>
          <div>
            <div className="text-base md:text-lg font-black text-gray-900 mb-0.5 md:mb-1">
              {isHighRain ? "Elevated" : "Normal"}
            </div>
            <p className="text-[11px] md:text-xs text-gray-500 leading-snug">
               {isHighRain 
                ? "Humid conditions post-rainfall increase the risk of fungal infections." 
                : "Standard prophylactic monitoring recommended."}
            </p>
          </div>
        </div>

        {/* Crop Context */}
        <div className="bg-emerald-50 p-3 md:p-4 rounded-xl border border-emerald-100 shadow-sm flex md:block items-center md:items-start gap-4 md:gap-0">
          <div className="flex flex-col md:flex-row md:items-center gap-1 md:gap-2 mb-0 md:mb-2 w-20 md:w-auto shrink-0">
            <Sprout size={18} className="text-emerald-600 hidden md:block"/>
            <h4 className="font-bold text-emerald-700 md:text-emerald-800 text-[10px] md:text-sm uppercase tracking-wider md:tracking-normal md:normal-case">Crop</h4>
          </div>
          <div>
            <div className="text-base md:text-lg font-black text-emerald-900 mb-0.5 md:mb-1">
               {selectedCrop ? selectedCrop : "Generic"}
            </div>
            <p className="text-[11px] md:text-xs text-emerald-700/80 leading-snug">
               {selectedCrop 
                ? `Advisory tailored for ${selectedCrop} growth stages.` 
                : "Select a crop above to receive tailored insights."}
            </p>
          </div>
        </div>
      </div>

    </div>
  );
}
