export type LanguageCode = 'en' | 'hi' | 'mr';

export const translations = {
  en: {
    // Navigation & Header
    "nav.title": "Panchayat Weather",
    "nav.myPanchayat": "My Panchayat",
    "nav.map": "Map",
    "nav.weather": "Weather",
    "nav.advisory": "Advisory",
    "nav.aiCopilot": "AI Copilot",
    "nav.dataModel": "Data & Model",

    // Panchayat Selector
    "panchayat.myPanchayat": "My Panchayat",
    "panchayat.select": "Select Panchayat",
    "panchayat.district": "District",
    "panchayat.block": "Block",
    "panchayat.panchayat": "Panchayat",
    "panchayat.noData": "No data available",

    // Weather
    "weather.today": "Today's Weather",
    "weather.rainfall": "Rainfall",
    "weather.temperature": "Temperature",
    "weather.humidity": "Humidity",
    "weather.wind": "Wind",
    "weather.details": "Weather Details",
    "weather.outlook7Day": "7-Day Outlook",
    "weather.unavailable": "Weather data is currently unavailable.",

    // Agriculture
    "ag.growing": "What are you growing?",
    "ag.rice": "Rice",
    "ag.soybean": "Soybean",
    "ag.maize": "Maize",
    "ag.vegetables": "Vegetables",
    "ag.sugarcane": "Sugarcane",
    "ag.advisory": "Agricultural Advisory",
    "ag.irrigation": "Irrigation",
    "ag.fieldWork": "Field Work",
    "ag.pestRisk": "Pest Risk",
    "ag.viewDetails": "View advisory details",
    "ag.hideDetails": "Hide advisory details",
    "ag.why": "WHY?",
    "ag.whatToWatch": "WHAT TO WATCH",
    "ag.dataUsed": "DATA USED",
    "ag.generic": "Generic",
    "ag.selectCrop": "Select a crop above to receive tailored insights.",
    "ag.tailoredFor": "Advisory tailored for {crop} growth stages.",
    "ag.monitor": "Monitor",
    "ag.maintain": "Maintain",
    "ag.delay": "Delay",
    "ag.favorable": "Favorable",
    "ag.elevated": "Elevated",
    "ag.normal": "Normal",
    "ag.contextUpdated": "Advisory context updated for {crop}",

    // AI Copilot
    "ai.title": "Panchayat Weather Copilot",
    "ai.ask": "Ask Panchayat AI",
    "ai.askPlaceholder": "Ask about your weather...",
    "ai.suggested": "Suggested questions",
    "ai.send": "Send",
    "ai.thinking": "Thinking...",
    "ai.retry": "Retry",
    "ai.unavailable": "AI assistant is temporarily unavailable.",
    "ai.suggestion1": "Will it rain tomorrow?",
    "ai.suggestion2": "Should I irrigate today?",
    "ai.suggestion3": "Explain today's weather.",
    "ai.grounded": "Grounded in",

    // Explanations
    "explain.whatDoesThisMean": "What does this mean?",
    "explain.whyDifferent": "Why is this different?",
    "explain.whyEstimate": "Why this estimate?",
    "explain.aiDownscaling": "AI Downscaling",

    // System
    "sys.loading": "Loading...",
    "sys.error": "Error",
    "sys.retry": "Retry",
    "sys.comingSoon": "Coming soon",
    "sys.prototype": "Prototype",
    "sys.decisionSupport": "Decision-support prototype. Interpretations are generated by static rules for demonstration purposes.",
    "sys.operationalUnavailable": "Operational forecast unavailable",
    
    // Data Section
    "data.validation": "Validation",
    "data.historical": "Historical experiment",
    "data.operational": "Operational forecast",
    "data.downscaling": "Downscaling",
    "data.technical": "Technical explanations"
  },
  hi: {
    // Navigation & Header
    "nav.title": "पंचायत मौसम",
    "nav.myPanchayat": "मेरी पंचायत",
    "nav.map": "नक्शा",
    "nav.weather": "मौसम",
    "nav.advisory": "कृषि सलाह",
    "nav.aiCopilot": "AI सहायक",
    "nav.dataModel": "डेटा और मॉडल",

    // Panchayat Selector
    "panchayat.myPanchayat": "मेरी पंचायत",
    "panchayat.select": "पंचायत चुनें",
    "panchayat.district": "ज़िला",
    "panchayat.block": "ब्लॉक",
    "panchayat.panchayat": "पंचायत",
    "panchayat.noData": "डेटा उपलब्ध नहीं है",

    // Weather
    "weather.today": "आज का मौसम",
    "weather.rainfall": "बारिश",
    "weather.temperature": "तापमान",
    "weather.humidity": "नमी",
    "weather.wind": "हवा",
    "weather.details": "मौसम की जानकारी",
    "weather.outlook7Day": "7-दिन का पूर्वानुमान",
    "weather.unavailable": "मौसम की जानकारी अभी उपलब्ध नहीं है।",

    // Agriculture
    "ag.growing": "आप क्या उगा रहे हैं?",
    "ag.rice": "धान",
    "ag.soybean": "सोयाबीन",
    "ag.maize": "मक्का",
    "ag.vegetables": "सब्ज़ियाँ",
    "ag.sugarcane": "गन्ना",
    "ag.advisory": "कृषि सलाह",
    "ag.irrigation": "सिंचाई",
    "ag.fieldWork": "खेत में काम",
    "ag.pestRisk": "कीटों का जोखिम",
    "ag.viewDetails": "सलाह की जानकारी देखें",
    "ag.hideDetails": "सलाह की जानकारी छिपाएँ",
    "ag.why": "क्यों?",
    "ag.whatToWatch": "क्या ध्यान रखें",
    "ag.dataUsed": "डेटा का उपयोग",
    "ag.generic": "सामान्य",
    "ag.selectCrop": "विशेष जानकारी के लिए ऊपर फसल चुनें।",
    "ag.tailoredFor": "{crop} के लिए विशेष सलाह।",
    "ag.monitor": "निगरानी करें",
    "ag.maintain": "जारी रखें",
    "ag.delay": "देरी करें",
    "ag.favorable": "अनुकूल",
    "ag.elevated": "अधिक",
    "ag.normal": "सामान्य",
    "ag.contextUpdated": "{crop} के लिए सलाह अपडेट की गई",

    // AI Copilot
    "ai.title": "पंचायत मौसम AI सहायक",
    "ai.ask": "पंचायत AI से पूछें",
    "ai.askPlaceholder": "अपने मौसम के बारे में पूछें...",
    "ai.suggested": "सुझाए गए प्रश्न",
    "ai.send": "भेजें",
    "ai.thinking": "सोच रहा है...",
    "ai.retry": "पुनः प्रयास करें",
    "ai.unavailable": "AI सहायक फिलहाल उपलब्ध नहीं है।",
    "ai.suggestion1": "क्या कल बारिश होगी?",
    "ai.suggestion2": "क्या मुझे आज सिंचाई करनी चाहिए?",
    "ai.suggestion3": "आज के मौसम को समझाइए।",
    "ai.grounded": "संदर्भित:",

    // Explanations
    "explain.whatDoesThisMean": "इसका क्या मतलब है?",
    "explain.whyDifferent": "यह अलग क्यों है?",
    "explain.whyEstimate": "यह अनुमान क्यों?",
    "explain.aiDownscaling": "AI डाउनस्केलिंग",

    // System
    "sys.loading": "लोड हो रहा है...",
    "sys.error": "त्रुटि",
    "sys.retry": "पुनः प्रयास करें",
    "sys.comingSoon": "जल्द उपलब्ध होगा",
    "sys.prototype": "प्रोटोटाइप",
    "sys.decisionSupport": "निर्णय-सहायता प्रोटोटाइप। व्याख्याएं प्रदर्शन के उद्देश्य से स्थिर नियमों द्वारा उत्पन्न की जाती हैं।",
    "sys.operationalUnavailable": "परिचालन पूर्वानुमान उपलब्ध नहीं है",

    // Data Section
    "data.validation": "सत्यापन",
    "data.historical": "ऐतिहासिक प्रयोग",
    "data.operational": "परिचालन पूर्वानुमान",
    "data.downscaling": "डाउनस्केलिंग",
    "data.technical": "तकनीकी स्पष्टीकरण"
  },
  mr: {
    // Navigation & Header
    "nav.title": "पंचायत हवामान",
    "nav.myPanchayat": "माझी पंचायत",
    "nav.map": "नकाशा",
    "nav.weather": "हवामान",
    "nav.advisory": "कृषी सल्ला",
    "nav.aiCopilot": "AI सहाय्यक",
    "nav.dataModel": "डेटा आणि मॉडेल",

    // Panchayat Selector
    "panchayat.myPanchayat": "माझी पंचायत",
    "panchayat.select": "पंचायत निवडा",
    "panchayat.district": "जिल्हा",
    "panchayat.block": "ब्लॉक",
    "panchayat.panchayat": "पंचायत",
    "panchayat.noData": "डेटा उपलब्ध नाही",

    // Weather
    "weather.today": "आजचे हवामान",
    "weather.rainfall": "पाऊस",
    "weather.temperature": "तापमान",
    "weather.humidity": "आर्द्रता",
    "weather.wind": "वारा",
    "weather.details": "हवामानाची माहिती",
    "weather.outlook7Day": "7-दिवसांचा अंदाज",
    "weather.unavailable": "हवामानाची माहिती सध्या उपलब्ध नाही.",

    // Agriculture
    "ag.growing": "तुम्ही काय पिकवत आहात?",
    "ag.rice": "तांदूळ",
    "ag.soybean": "सोयाबीन",
    "ag.maize": "मका",
    "ag.vegetables": "भाज्या",
    "ag.sugarcane": "ऊस",
    "ag.advisory": "कृषी सल्ला",
    "ag.irrigation": "सिंचन",
    "ag.fieldWork": "शेतातील कामे",
    "ag.pestRisk": "कीटकांचा धोका",
    "ag.viewDetails": "सल्ल्याची माहिती पहा",
    "ag.hideDetails": "सल्ल्याची माहिती लपवा",
    "ag.why": "का?",
    "ag.whatToWatch": "काय पहावे",
    "ag.dataUsed": "वापरलेला डेटा",
    "ag.generic": "सामान्य",
    "ag.selectCrop": "विशेष माहितीसाठी वर पीक निवडा.",
    "ag.tailoredFor": "{crop} साठी विशेष सल्ला.",
    "ag.monitor": "लक्ष ठेवा",
    "ag.maintain": "सुरू ठेवा",
    "ag.delay": "उशीर करा",
    "ag.favorable": "अनुकूल",
    "ag.elevated": "जास्त",
    "ag.normal": "सामान्य",
    "ag.contextUpdated": "{crop} साठी सल्ला अपडेट केला",

    // AI Copilot
    "ai.title": "पंचायत हवामान AI सहाय्यक",
    "ai.ask": "पंचायत AI ला विचारा",
    "ai.askPlaceholder": "तुमच्या हवामानाबद्दल विचारा...",
    "ai.suggested": "सुचविलेले प्रश्न",
    "ai.send": "पाठवा",
    "ai.thinking": "विचार करत आहे...",
    "ai.retry": "पुन्हा प्रयत्न करा",
    "ai.unavailable": "AI सहाय्यक सध्या उपलब्ध नाही.",
    "ai.suggestion1": "उद्या पाऊस पडेल का?",
    "ai.suggestion2": "आज सिंचन करावे का?",
    "ai.suggestion3": "आजचे हवामान समजावून सांगा.",
    "ai.grounded": "संदर्भ:",

    // Explanations
    "explain.whatDoesThisMean": "याचा काय अर्थ आहे?",
    "explain.whyDifferent": "हे वेगळे का?",
    "explain.whyEstimate": "हा अंदाज का?",
    "explain.aiDownscaling": "AI डाउनस्केलिंग",

    // System
    "sys.loading": "लोड करत आहे...",
    "sys.error": "त्रुटी",
    "sys.retry": "पुन्हा प्रयत्न करा",
    "sys.comingSoon": "लवकरच उपलब्ध",
    "sys.prototype": "प्रोटोटाइप",
    "sys.decisionSupport": "निर्णय-सहाय्य प्रोटोटाइप. स्पष्टीकरणे प्रात्यक्षिकासाठी स्थिर नियमांद्वारे तयार केली आहेत.",
    "sys.operationalUnavailable": "ऑपरेशनल अंदाज उपलब्ध नाही",

    // Data Section
    "data.validation": "सत्यापन",
    "data.historical": "ऐतिहासिक प्रयोग",
    "data.operational": "ऑपरेशनल अंदाज",
    "data.downscaling": "डाउनस्केलिंग",
    "data.technical": "तांत्रिक स्पष्टीकरण"
  }
};
